### ISSUE TITLE
Pyto media access

### ISSUE THREAD

**Issue by ifuchs** [ColdGrub1384/Pyto#118]
Can Pyto access the microphone and/or the camera? If so, does anyone have any examples of recording and playing back audio as well as grabbing images and/or video?

**Comment by ColdGrub1384** [comment]
For taking a photo or a video (but without audio), it can be done with `OpenCV`. Accessing the microphone cannot be done currently.

**Comment by ifuchs** [comment]
That would be nice for real-time capture and processing, maybe someday. 
In the meantime what is wrong with this code to capture and show an image on iPad?

> import cv2
> cap = cv2.VideoCapture(1)
> cap.set(3,640) #width=640
> cap.set(4,480) #height=480
> 
> while cap.isOpened():
>     ret, frame = cap.read()
> 
>     # Check if frame is not empty
>     if not ret:
>         continue
>     cap.release()
>     
>     if ret and frame is not None:
>         cv2.imshow('frame', frame)

**Comment by ColdGrub1384** [comment]
@ifuchs You should remove `cap.release()`, that closes the camera. The image will probably have wrong colors, that can be fixed with the `cvtColor` function. Also, Pyto provides a `autorotate` function to rotate the images to match the device's orientation.

```
import cv2
cap = cv2.VideoCapture(1)
cap.set(3,640) #width=640
cap.set(4,480) #height=480

while cap.isOpened():
    ret, frame = cap.read()

    # Check if frame is not empty
    if not ret:
        continue

    # Auto rotate camera
    frame = cv2.autorotate(frame, device)

    # Convert from BGR to RGB
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)    

    if ret and frame is not None:
        cv2.imshow('frame', frame)
```

**Comment by ifuchs** [comment]
Thanks! Is it possible for the display to show the image full screen?

**Comment by ColdGrub1384** [comment]
It's not supported by Pyto itself, but you can do it with `pyto_ui` and it's a bit laggy.

```python
import cv2
import threading
from PIL import Image
import pyto_ui as ui

exited = False

image_view = ui.ImageView()

def loop():
    cap = cv2.VideoCapture(1)
    cap.set(3,640) #width=640
    cap.set(4,480) #height=480
    
    while cap.isOpened() and not exited:
        ret, frame = cap.read()
    
        # Check if frame is not empty
        if not ret:
            continue
    
        # Auto rotate camera
        frame = cv2.autorotate(frame, 1)
    
        # Convert from BGR to RGB
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)    
    
        if ret and frame is not None:
            image_view.image = Image.fromarray(frame)

threading.Thread(target=loop).start()

ui.show_view(image_view, ui.PRESENTATION_MODE_FULLSCREEN)
exited = True
```

**Comment by ifuchs** [comment]
Thanks that works, though as you say, rather laggy.

**Comment by matthiasbirkich** [comment]
Dear Adrian Labbé, thank you for your work!
I have installed a lot of packages which are working well.
When I compare Pyto with Phytonista, I miss or do not know how to have following possibility. 
In settings I can not choose Photo-Folder, I guess...
1) direct access to the photo-library
I don’t use the right syntax sharing.open_url(⁨https://share.icloud.com/photos/0vEYl247qQfur1wNdEvo_rqUQ)
Are you or the community is so polite to explain me the right code to get the photo?
2) How can I get access to the iPad camera (with openCV ?)

thanx.
Best regards 
Matthias

**Comment by matthiasbirkich** [comment]
By the way,
When Pyto is generating error messages to your email-account, the following e-mail adress it not working: mailto:adrian@develobile.com
best regards, Matthias

**Comment by ColdGrub1384** [comment]
@matthiasbirkich For the moment, it’s not possible to have access to the photos library, but you can pick files. https://pyto.readthedocs.io/en/latest/sharing.html#sharing.FilePicker

With OpenCV, you can have access to the camera like this:

```

import cv2
cap = cv2.VideoCapture(1)
cap.set(3,640) #width=640
cap.set(4,480) #height=480

while cap.isOpened():
    ret, frame = cap.read()

    # Check if frame is not empty
    if not ret:
        continue

    # Auto rotate camera
    frame = cv2.autorotate(frame, device)

    # Convert from BGR to RGB
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)    

    if ret and frame is not None:
        cv2.imshow('frame', frame)
```

I changed my email address. I thought I also changed it in the code. I’ll update it.

**Comment by matthiasbirkich** [comment]
Adrian, thanks for your fast answer!
I tried to run the Filepicker code, but I failed, because my knowledge is very poor. Maybe I forgot to import the right lib?

NameError: name 'sharing' is not defined

The openCV code is running (Thank you!). But is taking pics continuously when I delete 
frame = cv2.autorotate(frame, device) 
I deleted the raw because it gives an error message device is not defined (frame i put to „1“).
I don’t have any clou, how I can get excess to the photo, or how to save the information of it.
Have a nice Sunday, best regards
Matthias 

P.S.: Is there planned to have a Forum for Pyto?

**Comment by matthiasbirkich** [comment]
Camera is also reachable by kivy.
https://kivy.org/doc/stable/api-kivy.uix.camera.html#kivy.uix.camera.Camera
But the package kivy is not running after installation:
Traceback (most recent call last):
  File "iCloud/Camera_Kivy.py", line 1, in <module>
    import kivy
  File "Documents/site-packages/kivy/__init__.py", line 333, in <module>
    mkdir(kivy_home_dir)
PermissionError: [Errno 1] Operation not permitted: '/private/var/mobile/Containers/Data/Application/88C09AC4-4280-4B77-8BCD-DAEEAFB77FF2/.kivy'
best regards
Matthias

**Comment by cclauss** [comment]
Are you sure you Pyto is a current version?  https://pyto.readthedocs.io/en/latest/sharing.html

> Is there planned to have a Forum for Pyto?

First line of __README.md__ says: Join the Pyto Discord channel: https://discord.gg/XCKkvJS

**Comment by matthiasbirkich** [comment]
Adrian, Thank you very much for the Photos module! I have recognized that a minute ago! I am able to handle filePicker as well now. I forgot to import the module sharing. Sorry.
Dear Christian Clauss,
I am afraid to join the Pyto Discord channel, because I thought you have to pay for it. Also it is not working:
„ Safari kann die Seite nicht öffnen, da die Adresse ungültig ist.“
„Safari is not able to open the site, because the adress is invalid.“
Best regards, Matthias
