### ISSUE TITLE
Multiple libraries  crash on import

### ISSUE THREAD

**Issue by marcosgeorgopoulos** [ColdGrub1384/Pyto#120]
Hi, 

I have an iPad Pro running iOS 13.2 I have purchased this through the App Store.

Whenever I try to import the pandas library it crashes the application. In fact it seems to crash on a lot of the libraries.

Can you please assist.

**Comment by cclauss** [comment]
Can you please reboot your iPad and try again?

**Comment by marcosgeorgopoulos** [comment]
Yeah I have tried rebooting twice, shutting down all other apps and uninstalling and reinstalling.

**Comment by marcosgeorgopoulos** [comment]
Here is an error I managed to capture in the interactive prompt. 


Python 3.8.0+ (default, Jan 19 2020, 02:10:45) 
[Clang 11.0.0 (clang-1100.0.33.12)] on ios
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import pandas as pd
C extension: 'normalize_date' from '__pandas__libs_tslibs_conversion' (built-in) not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
Traceback (most recent call last):
  File "Pyto.app/site-packages/pandas/__init__.py", line 30, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "Pyto.app/site-packages/pandas/_libs/__init__.py", line 3, in <module>
    from .tslibs import (
  File "Pyto.app/site-packages/pandas/_libs/tslibs/__init__.py", line 3, in <module>
    from .conversion import localize_pydatetime, normalize_date
ImportError: cannot import name 'normalize_date' from '__pandas__libs_tslibs_conversion' (built-in)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "Pyto.app/site-packages/extensionsimporter.py", line 172, in load_module
    importMod()
  File "Pyto.app/site-packages/extensionsimporter.py", line 164, in importMod
    mod = importlib.__import__(f)
  File "Pyto.app/site-packages/pandas/__init__.py", line 34, in <module>
    raise ImportError(
ImportError: C extension: 'normalize_date' from '__pandas__libs_tslibs_conversion' (built-in) not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.

**Comment by marcosgeorgopoulos** [comment]
It is also crashing on my iPhone X running 13.3.

There seems to be an issue with the latest release.  I’m happy to help troubleshoot if there is anything I can do

**Comment by marcosgeorgopoulos** [comment]
I’ve done some more testing and numpy and matplotlib are causing a crash as well

**Comment by marcosgeorgopoulos** [comment]
Doing some more testing with pdb: 

Numpy imports fine. 
Matplotlib import crashes
Pandas import crashes
Cv2 imports fine 
Scipy imports fine.

**Comment by marcosgeorgopoulos** [comment]
Importing bs4 is crashing as well.  Details below

-> from bs4 import BeautifulSoup
(Pdb) n
Traceback (most recent call last):
  File "Pyto.app/site-packages/pdb.py", line 1705, in main
    pdb._runscript(mainpyfile)
  File "Pyto.app/site-packages/pdb.py", line 1574, in _runscript
    self.run(statement)
  File "/var/containers/Bundle/Application/EC1C3BDC-0D0E-4975-A237-DE6A4E1EC62A/Pyto.app/Frameworks/Python.framework/python38.zip/bdb.py", line 587, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/soup/cisco.py", line 1, in <module>
    from bs4 import BeautifulSoup
  File "Pyto.app/site-packages/bs4/__init__.py", line 34, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "Pyto.app/site-packages/bs4/builder/__init__.py", line 341, in <module>
    from . import _lxml
  File "Pyto.app/site-packages/bs4/builder/_lxml.py", line 16, in <module>
    from lxml import etree
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "Pyto.app/site-packages/extensionsimporter.py", line 322, in load_module
    importMod()
  File "Pyto.app/site-packages/extensionsimporter.py", line 318, in importMod
    mod = importlib.__import__(f)
  File "src/lxml/etree.pyx", line 1, in init lxml.etree
  File "src/lxml/etree.pyx", line 1, in __Pyx_PyMODINIT_FUNC PyInit_etree(void)
  File "/var/containers/Bundle/Application/EC1C3BDC-0D0E-4975-A237-DE6A4E1EC62A/Pyto.app/Frameworks/Python.framework/python38.zip/bdb.py", line 90, in trace_dispatch
    return self.dispatch_call(frame, arg)
  File "/var/containers/Bundle/Application/EC1C3BDC-0D0E-4975-A237-DE6A4E1EC62A/Pyto.app/Frameworks/Python.framework/python38.zip/bdb.py", line 128, in dispatch_call
    if not (self.stop_here(frame) or self.break_anywhere(frame)):
  File "/var/containers/Bundle/Application/EC1C3BDC-0D0E-4975-A237-DE6A4E1EC62A/Pyto.app/Frameworks/Python.framework/python38.zip/bdb.py", line 252, in break_anywhere
    return self.canonic(frame.f_code.co_filename) in self.breaks
  File "/var/containers/Bundle/Application/EC1C3BDC-0D0E-4975-A237-DE6A4E1EC62A/Pyto.app/Frameworks/Python.framework/python38.zip/bdb.py", line 49, in canonic
    canonic = os.path.abspath(filename)
  File "/var/containers/Bundle/Application/EC1C3BDC-0D0E-4975-A237-DE6A4E1EC62A/Pyto.app/Frameworks/Python.framework/python38.zip/posixpath.py", line 379, in abspath
    cwd = os.getcwd()
PermissionError: [Errno 1] Operation not permitted
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /var/containers/Bundle/Application/EC1C3BDC-0D0E-4975-A237-DE6A4E1EC62A/Pyto.app/Frameworks/Python.framework/python38.zip/posixpath.py(379)abspath()
-> cwd = os.getcwd()

**Comment by ColdGrub1384** [comment]
That will be fixed in a new update that I already submitted. I’m so sorry for that! It’s strange because I literally done nothing to fix this, seems to be a build issue or something like that. I tested the build submitted to the App Store and it will work perfectly on the next update. Apple is currently reviewing my apps fast, so the update should be released today.

**Comment by marcosgeorgopoulos** [comment]
Thank you very much for the fast response. Good to see it’s a quick fix.  Cheers

**Comment by ColdGrub1384** [comment]
The update was approved 5 hours ago but the update isn't on the App Store yet. The App Store is really slow at processing updates 😣

**Comment by marcosgeorgopoulos** [comment]
These things cannot be helped. I am very impressed with your responsiveness to the issue.

**Comment by marcosgeorgopoulos** [comment]
Thank you the issue has been resolved with the latest release.
