### ISSUE TITLE
Cannot import KMeans from sklearn

### ISSUE THREAD

**Issue by ForceBru** [ColdGrub1384/Pyto#129]
I'm running this code:

```
print("Importing Pandas...")
import pandas as pd
print("Imported Pandas!\nImporting KMeans...")
from sklearn.cluster import KMeans
print("Imported KMeans!")
```

Getting this error:

```
Importing Pandas...
Imported Pandas!
Importing KMeans...
Traceback (most recent call last):
  File "Documents/Test.py", line 4, in <module>
    from sklearn.cluster import KMeans
  File "Pyto.app/site-packages/sklearn/cluster/__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "Pyto.app/site-packages/sklearn/cluster/_spectral.py", line 15, in <module>
    from ..metrics.pairwise import pairwise_kernels
  File "Pyto.app/site-packages/sklearn/metrics/__init__.py", line 7, in <module>
    from ._ranking import auc
  File "Pyto.app/site-packages/sklearn/metrics/_ranking.py", line 32, in <module>
    from ..utils.extmath import stable_cumsum
  File "Pyto.app/site-packages/sklearn/utils/extmath.py", line 21, in <module>
    from .sparsefuncs_fast import csr_row_norms
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "Pyto.app/site-packages/extensionsimporter.py", line 426, in load_module
    importMod()
  File "Pyto.app/site-packages/extensionsimporter.py", line 422, in importMod
    mod = importlib.__import__(f)
TypeError: Shared Cython type cython_function_or_method has the wrong size, try recompiling
```

Restarting the app doesn't help. 

Pyto version 11.3.11 (1) 1 Feb 2020 at 01:55

**Comment by ColdGrub1384** [comment]
Thanks!

**Comment by ForceBru** [comment]
Yep, works in 11.3.12, thanks!
