### ISSUE TITLE
Pyodbc

### ISSUE THREAD

**Issue by ifuchs** [ColdGrub1384/Pyto#131]
I would like to access an MS SQL dB and need pyodbc. However if I try to do a pip install pyodbc, I get:

Querying PyPI ... 
Downloading package ...
Downloading ████████████████████████████████ 100%
Extracting archive file ...
Reading gzip file.
Extracting files.
Archive extracted.
Running setup file ...
[Errno 1] Operation not permitted
PipError('failed to find packages or py_modules arguments in setup call')
Failed to run setup.py
Fall back to directory guessing ...
Error: Cannot locate packages. Manual installation required.

Has anyone gotten Pyto to connect to an SQL server?

**Comment by cclauss** [comment]
Pyto uses https://github.com/ColdGrub1384/Pyto/tree/master/site-packages/rubicon/objc

**Comment by ifuchs** [comment]
Thanks but I’m not quite sure how that helps with the problem of accessing an MSSQL database.

**Comment by cclauss** [comment]
https://github.com/mkleehammer/pyodbc is Python 63.6%,  C++ 33.0%,  C 3.4%

**Comment by ifuchs** [comment]
Is there a driver that will permit sqlalchemy to communicate with MS SQL Server? pyodbc requires c libraries so it cannot be installed. MySQL and pymysql work fine but I need to connect to MS SQL.

**Comment by ifuchs** [comment]
I found the pypyodbc driver which is pure python but if I import it I get this error:

>>> import pypyodbc
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/mobile/Containers/Shared/AppGroup/05D14C00-CCAC-4E98-A3CC-96C6944B8534/Pythonista3/Documents/site-packages-2/pypyodbc.py", line 440, in <module>
    raise OdbcNoLibrary('ODBC Library is not found. Is LD_LIBRARY_PATH set?')
pypyodbc.OdbcNoLibrary: 'ODBC Library is not found. Is LD_LIBRARY_PATH set?'
