### ISSUE TITLE
Feature request: scrapy

### ISSUE THREAD

**Issue by ifuchs** [ColdGrub1384/Pyto#143]
I tried using Pip to install scrapy but there appear to be some dependencies which are not there:

>>> import scrapy
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "Documents/site-packages/scrapy/__init__.py", line 27, in <module>
    from scrapy import _monkeypatches
  File "Documents/site-packages/scrapy/_monkeypatches.py", line 6, in <module>
    import twisted.persisted.styles  # NOQA
ModuleNotFoundError: No module named 'twisted

**Comment by cclauss** [comment]
What happens if you `pip install twisted` first?

**Comment by ifuchs** [comment]
I tried installing Twisted and for some reason it will not install. I get
this result ‘local variable d referenced before assignment’. However I
suspect that scrapy wouldn’t work anyway as I am unsure as to whether it
has non c dependencies. Is any else able to install it?

**Comment by cclauss** [comment]
Go to the twisted repo on GitHub and click the colored bar to see the languages used...

![Twisted languages used](https://user-images.githubusercontent.com/3709715/76769129-4fd2de00-679c-11ea-9ea7-c4a8bb6a683c.png)

Then click [`C 0.1%`](https://github.com/twisted/twisted/search?l=c) to see the three C files.  Perhaps they define `d`.

**Comment by ifuchs** [comment]
I think the only way to get twisted and scrapy installed is for it to be
added by the developer.

**Comment by cclauss** [comment]
Twisted yes.  Scrapy no.
* To reduce app bloat, we should avoid bundling modules that the user can install on their own.

**Comment by ifuchs** [comment]
I agree unless there is something else that prevents scrapy from being installed. In that case, I guess it can just get added to the list :-)
