### ISSUE TITLE
Pytube error

### ISSUE THREAD

**Issue by ifuchs** [ColdGrub1384/Pyto#145]
I installed pytube but import gives:
```
In Documents/mpl-data/stylelib/classic.mplstyle: 
The savefig.frameon rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In Documents/mpl-data/stylelib/classic.mplstyle: 
The verbose.level rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In Documents/mpl-data/stylelib/classic.mplstyle: 
The verbose.fileo rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In Documents/mpl-data/stylelib/_classic_test.mplstyle: 
The savefig.frameon rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In Documents/mpl-data/stylelib/_classic_test.mplstyle: 
The verbose.level rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In Documents/mpl-data/stylelib/_classic_test.mplstyle: 
The verbose.fileo rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
Traceback (most recent call last):
  File "Documents/download_youtube.py", line 1, in <module>
    from pytube import YouTube
  File "Documents/site-packages/pytube/__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "Documents/site-packages/pytube/streams.py", line 17, in <module>
    from pytube import extract
  File "Documents/site-packages/pytube/extract.py", line 7, in <module>
    from pytube.compat import quote
ImportError: cannot import name 'quote' from 'pytube.compat' (Documents/site-packages/pytube/compat.py) 
```

**Comment by cclauss** [comment]
The deprecation warnings are just warnings and can be safely ignored.

The ImportError is discussed upstream https://github.com/nficano/pytube/issues/570

**Comment by ifuchs** [comment]
Thanks. It appears the solution is pytube3.

**Comment by cclauss** [comment]
Can this issue be closed?
