### ISSUE TITLE
Numpy integer problem

### ISSUE THREAD

**Issue by matthiasbirkich** [ColdGrub1384/Pyto#146]
Dear developers,

I get an Error directly on line 1 
```
import colour

Traceback (most recent call last):
  File "Pyto.app/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Documents/ColorPyto/00Python.py", line 1, in <module>
    import colour
  File "Documents/site-packages/colour/__init__.py", line 139, in <module>
    from .notation import (MUNSELL_COLOURS, MUNSELL_VALUE_METHODS,
  File "Documents/site-packages/colour/notation/__init__.py", line 12, in <module>
    from .munsell import MUNSELL_VALUE_METHODS
  File "Documents/site-packages/colour/notation/munsell.py", line 134, in <module>
    from colour.volume import is_within_macadam_limits
  File "Documents/site-packages/colour/volume/__init__.py", line 10, in <module>
    from .spectrum import (generate_pulse_waves, XYZ_outer_surface,
  File "Documents/site-packages/colour/volume/spectrum.py", line 133, in <module>
    illuminant=sd_ones(STANDARD_OBSERVERS_CMFS[
  File "Documents/site-packages/colour/colorimetry/generation.py", line 160, in sd_ones
    return sd_constant(1, shape)
  File "Documents/site-packages/colour/colorimetry/generation.py", line 94, in sd_constant
    wavelengths = shape.range(dtype)
  File "Documents/site-packages/colour/colorimetry/spectrum.py", line 455, in range
    range_, current_interval = np.linspace(
  File "<__array_function__ internals>", line 5, in linspace
  File "Pyto.app/site-packages/numpy/core/function_base.py", line 119, in linspace
    raise TypeError(
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
```

**Comment by matthiasbirkich** [comment]
After reinstall of the colour science package everything is ok.
