### ISSUE TITLE
Import plotnine fails

### ISSUE THREAD

**Issue by ifuchs** [ColdGrub1384/Pyto#151]
I pip installed plotnine and its dependencies without error. However, if I try to import it, I get:

```>>>import plotnine
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "Documents/site-packages/plotnine/__init__.py", line 1, in <module>
    from .qplot import qplot            # noqa: F401
  File "Documents/site-packages/plotnine/qplot.py", line 9, in <module>
    from .ggplot import ggplot
  File "Documents/site-packages/plotnine/ggplot.py", line 18, in <module>
    from .facets import facet_null
  File "Documents/site-packages/plotnine/facets/__init__.py", line 1, in <module>
    from .facet_grid import facet_grid
  File "Documents/site-packages/plotnine/facets/facet_grid.py", line 6, in <module>
    from .facet import facet, layout_null, combine_vars, add_missing_facets
  File "Documents/site-packages/plotnine/facets/facet.py", line 11, in <module>
    from ..scales.scales import Scales
  File "Documents/site-packages/plotnine/scales/__init__.py", line 83, in <module>
    from .limits import xlim, ylim, lims, expand_limits
  File "Documents/site-packages/plotnine/scales/limits.py", line 8, in <module>
    from ..geoms import geom_blank
  File "Documents/site-packages/plotnine/geoms/__init__.py", line 6, in <module>
    from .geom_abline import geom_abline
  File "Documents/site-packages/plotnine/geoms/geom_abline.py", line 9, in <module>
    from .geom import geom
  File "Documents/site-packages/plotnine/geoms/geom.py", line 3, in <module>
    from ..stats.stat import stat
  File "Documents/site-packages/plotnine/stats/__init__.py", line 6, in <module>
    from .stat_density import stat_density
  File "Documents/site-packages/plotnine/stats/stat_density.py", line 5, in <module>
    import statsmodels.api as sm
  File "Documents/site-packages/statsmodels/api.py", line 11, in <module>
    from .regression.recursive_ls import RecursiveLS
  File "Documents/site-packages/statsmodels/regression/recursive_ls.py", line 14, in <module>
    from statsmodels.tsa.statespace.mlemodel import (
  File "Documents/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 32, in <module>
    from .simulation_smoother import SimulationSmoother
  File "Documents/site-packages/statsmodels/tsa/statespace/simulation_smoother.py", line 9, in <module>
    from .kalman_smoother import KalmanSmoother
  File "Documents/site-packages/statsmodels/tsa/statespace/kalman_smoother.py", line 10, in <module>
    from statsmodels.tsa.statespace.representation import OptionWrapper
  File "Documents/site-packages/statsmodels/tsa/statespace/representation.py", line 9, in <module>
    from .tools import (
  File "Documents/site-packages/statsmodels/tsa/statespace/tools.py", line 14, in <module>
    from . import (_initialization, _representation, _kalman_filter,
ImportError: cannot import name '_initialization' from 'statsmodels.tsa.statespace' (Documents/site-packages/statsmodels/tsa/statespace/__init__.py)```

**Comment by cclauss** [comment]
Please put three backticks at the top of the log and three backticks at the bottom of the log so that it is readable.

**Comment by cclauss** [comment]
https://github.com/statsmodels/statsmodels/tree/master/statsmodels/tsa/statespace The file in question is a Cython compiled file.

**Comment by ifuchs** [comment]
That’s too bad. Perhaps plotnine support could be added to the list of desired additions.
