### ISSUE TITLE
issue with ui.GestureRecognizer

### ISSUE THREAD

**Issue by 7points** [ColdGrub1384/Pyto#166]
When running the scripts below, you can push the testbox without problems. If you run the main script a second time, you get the following message:
Traceback (most recent call last):
  File "Pyto.app/scripts_runner.py", line 32, in <module>
    exec(code)
  File "<string>", line 3, in <module>
AttributeError: module '_values' has no attribute 'ijupohwxvz'

# main.py
```
import pyto_ui as ui
from elements import uilib

view = ui.View()
view.background_color = ui.COLOR_DARK_GRAY
view.frame = 0, 0, 200, 200

x = uilib()
x.frame = 50, 50, 100, 100
x.build()
view.add_subview(x.box)

ui.show_view(view, ui.PRESENTATION_MODE_SHEET)
```
# elements.py
```
import pyto_ui as ui

class uilib():
    def __init__(self):
        self.box = None
        self.frame = 0, 0, 50, 50
        
    def pressed(self, sender):
        self.box.background_color = ui.Color.rgb(255, 0, 255, 1)

    def build(self):
        self.box = ui.View()
        self.box.background_color = ui.Color.rgb(255, 0, 0, 1)
        self.box.frame = self.frame

        self.gesture = ui.GestureRecognizer(ui.GESTURE_TYPE_TAP)
        self.gesture.action = self.pressed
        self.box.add_gesture_recognizer(self.gesture)
```

**Comment by ColdGrub1384** [comment]
Thank you!
