### ISSUE TITLE
cryptography can't be imported

### ISSUE THREAD

**Issue by 7points** [ColdGrub1384/Pyto#181]
Since last version of pyto 11.10.1 (5) there has been a problem with cryptography when the module is imported.

```
import cryptography

'''
Traceback (most recent call last):
  File "/private/var/mobile/Library/Mobile Documents/com~apple~CloudDocs/Pyto/cryptography.py", line 2, in <module>
    import cryptography
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "Pyto.app/site-packages/extensionsimporter.py", line 686, in load_module
    c.init_cryptography()
  File "/var/mobile/Containers/Data/Application/4B4C8228-2510-41D9-8B96-3F79D11B24DD/Library/python38/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/var/mobile/Containers/Data/Application/4B4C8228-2510-41D9-8B96-3F79D11B24DD/Library/python38/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, init_cryptography): symbol not found
'''
```

**Comment by cclauss** [comment]
Related to #33 and #77

**Comment by ColdGrub1384** [comment]
Thanks. I submitted an update to the App Store that fixed that. I should be available very soon.

**Comment by ColdGrub1384** [comment]
That's now fixed
