### ISSUE TITLE
Add pyvips 

### ISSUE THREAD

**Issue by comfortablynick** [ColdGrub1384/Pyto#185]
Is it possible to add pyvips (libvips library Python API)? I had a project I was writing in Python and I’d love to be able to use it in Pyto. I am using Pillow too, but I have some code that works a lot better and faster in vips.

**Comment by cclauss** [comment]
What happens when you pip install it into Pyto?

**Comment by comfortablynick** [comment]
```
python -m pip install pyvips
Querying PyPI ... 
Downloading package ...
Downloading ████████████████████████████████ 100%
Extracting archive file ...
Reading gzip file.
Extracting files.
Archive extracted.
Running setup file ...
Package installed: pyvips
Dependency available in Pyto bundle : cffi
Installing dependency: pkgconfig (required by: pyvips)
Querying PyPI ... 
Downloading package ...
Downloading ████████████████████████████████ 100%
Installing wheel: pkgconfig-1.5.1-py2.py3-none-any.whl...
Package installed: pkgconfig
Error: unknown command: None
```
Here’s what happens if I do `import pyvips` in the REPL:
```
ModuleNotFoundError: No module named '_libvips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Library/python38/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "Documents/site-packages/pyvips/__init__.py", line 70, in <module>
    gobject_lib = ffi.dlopen(_gobject_libname)
  File "Pyto.app/site-packages/cffi/api.py", line 146, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "Pyto.app/site-packages/cffi/api.py", line 828, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "Pyto.app/site-packages/cffi/api.py", line 823, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'libgobject-2.0.so.0': dlopen(libgobject-2.0.so.0, 0x0002): dlopen(): file not found: libgobject-2.0.so.0.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libgobject-2.0.so.0'
```

**Comment by cclauss** [comment]
It seems to be failing on `pkgconfig`.  What happens if you try to directly pip install pkgconfig?

**Comment by comfortablynick** [comment]
python -m pip install pkgconfig
    Error: Package already installed
    Error: unknown command: None

**Comment by comfortablynick** [comment]
I uninstalled everything in `pip list` and I also downloaded all optional modules. Something got rid of the `Error: unknown command: None` from `pip install`. Everything installs properly via `pip`, but I still get the above regarding the missing C libraries.

**Comment by ColdGrub1384** [comment]
I fixed the `Error: unknown command: None` message on the last update. I may add `pyvips` on an update, but for the moment it can't be installed due to C extensions.

**Comment by comfortablynick** [comment]
Yes, that's effectively what I was asking for; sorry I wasn't clear in my original post. If you could add the C extensions to Pyto in an update, that would be great. Thanks for considering!
