### ISSUE TITLE
Discord.py raises RuntimeError

### ISSUE THREAD

**Issue by iFrostFox** [ColdGrub1384/Pyto#201]
For whatever reason any bot that I write doesn’t work, it always raises an runtime error, even the expamle bots don’t work

bot.py:
```python
import os
import random
from discord.ext import commands

TOKEN = 'secret'

bot = commands.Bot(command_prefix='!')
@bot.command(name='random_letter', help='Responds with a random letter')
async def random_letter(x):
    letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

    response = random.choice(letters)
    await x.send(response)

bot.run(TOKEN)
```

It should normally run and show a random letter when I type !random_letter

Actual Results

But this error happens:
```python
Traceback (most recent call last):
  File "Documents/bot.py", line 7, in <module>
    bot = commands.Bot(command_prefix='!')
  File "Documents/site-packages/discord/ext/commands/bot.py", line 99, in __init__
    super().__init__(**options)
  File "Documents/site-packages/discord/ext/commands/core.py", line 1031, in __init__
    super().__init__(*args, **kwargs)
  File "Documents/site-packages/discord/client.py", line 206, in __init__
    self.loop = asyncio.get_event_loop() if loop is None else loop
  File "Library/python38/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
```

I asked this at stackoverflow and discord.py’s repo but they said that it’s an error caused by the ide, why is this happening at pyto and how can I solve it?

**Comment by ColdGrub1384** [comment]
That's because Pyto runs script in threads but I think I have an idea on how to solve this in the app level. For the moment, try running this before running the bot:

```python3
import asyncio

loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
```

**Comment by iFrostFox** [comment]
Thanks for your reply, I did it it no longer gives an Runtim Error but now this happens:
```python
Traceback (most recent call last):
  File "Documents/bot.py", line 23, in <module>
    bot.run(TOKEN)
  File "Documents/site-packages/discord/client.py", line 614, in run
    loop.add_signal_handler(signal.SIGINT, lambda: loop.stop())
  File "Library/python38/asyncio/unix_events.py", line 88, in add_signal_handler
    self._check_signal(sig)
  File "Library/python38/asyncio/unix_events.py", line 174, in _check_signal
    if sig not in signal.valid_signals():
AttributeError: module 'signal' has no attribute 'valid_signals'
```

**Comment by ColdGrub1384** [comment]
Try this:

```python3
def add_signal_handler(s, f):
    return
            
loop = asyncio.new_event_loop()
loop.add_signal_handler = add_signal_handler
asyncio.set_event_loop(loop)
```

**Comment by ColdGrub1384** [comment]
Try this:

```python3
def add_signal_handler(s, f):
    return
            
loop = asyncio.new_event_loop()
loop.add_signal_handler = add_signal_handler
asyncio.set_event_loop(loop)
```

**Comment by iFrostFox** [comment]
Thanks, it works now

**Comment by ColdGrub1384** [comment]
It should work without additional code in the last update.
