### ISSUE TITLE
Error while using Skyfield

### ISSUE THREAD

**Issue by victordomingos** [ColdGrub1384/Pyto#29]
I have been experimenting with `skyfield` and noticed that a bit of code from my script [`planets.py`](https://github.com/victordomingos/telescope-planner) crashes on Pyto, but not on other Python environments, like macOS or iOS/Pythonista). Not sure about what is causing this, but could be a bug on Pyto, or something related to NumPy.

```

Traceback (most recent call last):
  File "/privateDocuments/modules/jplephem/spk.py", line 152, in generate
    initial_epoch, interval_length, coefficients = self._data
AttributeError: 'Segment' object has no attribute '_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "iCloud/telescope-planner/planets.py", line 38, in <module>
    planet_astro = here.at(t).observe(p)
  File "/privateDocuments/modules/skyfield/errors.py", line 37, in wrapper
    return method(self, jd)
  File "/privateDocuments/modules/skyfield/vectorlib.py", line 74, in at
    p, v, observer_data.gcrs_position, message = self._at(t)
  File "/privateDocuments/modules/skyfield/vectorlib.py", line 184, in _at
    p2, v2, gcrs_position, message = segment._at(t)
  File "/privateDocuments/modules/skyfield/jpllib.py", line 207, in _at
    position, velocity = self.spk_segment.compute_and_differentiate(t.tdb)
  File "/privateDocuments/modules/jplephem/spk.py", line 111, in compute_and_differentiate
    return tuple(self.generate(tdb, tdb2))
  File "/privateDocuments/modules/jplephem/spk.py", line 154, in generate
    self._data = self._load()
  File "/privateDocuments/modules/jplephem/spk.py", line 130, in _load
    coefficients.shape = (int(n), rsize)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
```

**Comment by ColdGrub1384** [comment]
Could you check which Numpy version do you have on the Mac? Pythonista has NumPy 1.8.0 and Pyto has 1.16.1. It could be a version incompatibility error: https://stackoverflow.com/a/44669924/7515957

**Comment by victordomingos** [comment]
On Mac: NumPy 1.16.2

**Comment by ColdGrub1384** [comment]
I tested and I got that result:

```
[                                 ]   0% de421.bsp
[                                 ]   1% de421.bsp
[#                                ]   3% de421.bsp
[#                                ]   4% de421.bsp
[##                               ]   6% de421.bsp
[##                               ]   7% de421.bsp
[###                              ]   9% de421.bsp
[####                             ]  12% de421.bsp
[#####                            ]  16% de421.bsp
[#####                            ]  17% de421.bsp
[######                           ]  19% de421.bsp
[#######                          ]  21% de421.bsp
[#######                          ]  22% de421.bsp
[########                         ]  24% de421.bsp
[#########                        ]  27% de421.bsp
[##########                       ]  31% de421.bsp
[###########                      ]  33% de421.bsp
[###########                      ]  35% de421.bsp
[###########                      ]  35% de421.bsp
[#############                    ]  39% de421.bsp
[#############                    ]  40% de421.bsp
[#############                    ]  41% de421.bsp
[##############                   ]  43% de421.bsp
[###############                  ]  45% de421.bsp
[###############                  ]  46% de421.bsp
[################                 ]  48% de421.bsp
[################                 ]  50% de421.bsp
[#################                ]  53% de421.bsp
[##################               ]  55% de421.bsp
[###################              ]  58% de421.bsp
[####################             ]  60% de421.bsp
[####################             ]  61% de421.bsp
[#####################            ]  63% de421.bsp
[#####################            ]  64% de421.bsp
[#####################            ]  65% de421.bsp
[######################           ]  66% de421.bsp
[######################           ]  67% de421.bsp
[#######################          ]  69% de421.bsp
[#######################          ]  71% de421.bsp
[########################         ]  72% de421.bsp
[########################         ]  74% de421.bsp
[#########################        ]  76% de421.bsp
[#########################        ]  77% de421.bsp
[##########################       ]  78% de421.bsp
[###########################      ]  81% de421.bsp
[###########################      ]  82% de421.bsp
[############################     ]  84% de421.bsp
[############################     ]  85% de421.bsp
[#############################    ]  88% de421.bsp
[##############################   ]  91% de421.bsp
[##############################   ]  92% de421.bsp
[###############################  ]  94% de421.bsp
[################################ ]  96% de421.bsp
[################################ ]  98% de421.bsp
[#################################]  99% de421.bsp
[#################################] 100% de421.bsp

[#################################] 100% deltat.data

[#################################] 100% deltat.preds

[#################################] 100% Leap_Second.dat




Santiago -33.45130N, -70.66530E

UTC:   2019-03-24 02:56:48.514000+00:00
Local: 2019-03-24 02:56:48.514000+00:00 



Solar System:
=============

MOON:
     ALT: 23deg 15' 19.0" 
     AZ: 88deg 17' 21.9"

These are not visible:
SUN, MERCURY, VENUS, MARS, JUPITER, URANUS, NEPTUNE, PLUTO


Stars and other deep sky objects:
=================================


These are not visible:
POLARIS, BARNARD

```

Maybe the dependencies are not updated. Have you installed `skyfield` from the `PyPi` page?

**Comment by cclauss** [comment]
That test was on iOS or Mac?  I think it is very telling that POLARIS is not visible. ⭐️

**Comment by ColdGrub1384** [comment]
I tested on iOS

**Comment by victordomingos** [comment]
I installed skyfield using the PyPI section in Pyto. Meanwhile, I have uninstalled it and deleted the downloaded data files. I tried again and get the same result...

Error from this line:

`planet_astro = here.at(t).observe(p)`

Full trace back:

```

[                                 ]   0% de421.bsp
[                                 ]   2% de421.bsp
[#                                ]   5% de421.bsp
[###                              ]   9% de421.bsp
[###                              ]  10% de421.bsp
[####                             ]  14% de421.bsp
[#####                            ]  17% de421.bsp
[######                           ]  20% de421.bsp
[########                         ]  24% de421.bsp
[#########                        ]  28% de421.bsp
[##########                       ]  32% de421.bsp
[###########                      ]  35% de421.bsp
[#############                    ]  41% de421.bsp
[###############                  ]  46% de421.bsp
[################                 ]  50% de421.bsp
[##################               ]  55% de421.bsp
[###################              ]  59% de421.bsp
[#####################            ]  63% de421.bsp
[######################           ]  67% de421.bsp
[########################         ]  72% de421.bsp
[##########################       ]  78% de421.bsp
[###########################      ]  81% de421.bsp
[############################     ]  86% de421.bsp
[##############################   ]  90% de421.bsp
[###############################  ]  95% de421.bsp
[#################################] 100% de421.bsp

[#################################] 100% deltat.data

[#################################] 100% deltat.preds

[#################################] 100% Leap_Second.dat




Porto 41.14860N, -8.61100E

UTC:   2019-03-24 14:28:08.021000+00:00
Local: 2019-03-24 14:28:08.021000+00:00 



Solar System:
=============

Traceback (most recent call last):
  File "/privateDocuments/modules/jplephem/spk.py", line 152, in generate
    initial_epoch, interval_length, coefficients = self._data
AttributeError: 'Segment' object has no attribute '_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "iCloud/telescope-planner/planets-gh.py", line 38, in <module>
    planet_astro = here.at(t).observe(p)
  File "/privateDocuments/modules/skyfield/errors.py", line 37, in wrapper
    return method(self, jd)
  File "/privateDocuments/modules/skyfield/vectorlib.py", line 74, in at
    p, v, observer_data.gcrs_position, message = self._at(t)
  File "/privateDocuments/modules/skyfield/vectorlib.py", line 184, in _at
    p2, v2, gcrs_position, message = segment._at(t)
  File "/privateDocuments/modules/skyfield/jpllib.py", line 207, in _at
    position, velocity = self.spk_segment.compute_and_differentiate(t.tdb)
  File "/privateDocuments/modules/jplephem/spk.py", line 111, in compute_and_differentiate
    return tuple(self.generate(tdb, tdb2))
  File "/privateDocuments/modules/jplephem/spk.py", line 154, in generate
    self._data = self._load()
  File "/privateDocuments/modules/jplephem/spk.py", line 130, in _load
    coefficients.shape = (int(n), rsize)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
```

**Comment by victordomingos** [comment]
@cclauss That’s right. Polaris being below the horizon is expected when the detected location is somewhere in the south hemisphere.

**Comment by cclauss** [comment]
It was a joke my friend.
