### ISSUE TITLE
‘Import webbrowser’ raises TypeError

### ISSUE THREAD

**Issue by cclauss** [ColdGrub1384/Pyto#32]
__import webbrowser__
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "Pyto.app/Frameworks/Python.framework/python37.zip/webbrowser.py", line 622, in <module>
    register("mobilesafari", None, MobileSafari(), -1)
TypeError: register() takes from 2 to 3 positional arguments but 4 were given
```

**Comment by ColdGrub1384** [comment]
Thank you. Fixed by 8111c9701fd25cc2d59259d843d6e8c699a060df
