### ISSUE TITLE
pip install github3.py is not working

### ISSUE THREAD

**Issue by cclauss** [ColdGrub1384/Pyto#33]
Seems to take several steps but then seems to fail.  Perhaps a C code issue?

**Comment by ColdGrub1384** [comment]
It worked for me. Could you please give me the output?

**Comment by cclauss** [comment]
```
>>> import github3
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/privateDocuments/modules/github3/__init__.py", line 24, in <module>
    from .api import (
  File "/privateDocuments/modules/github3/api.py", line 13, in <module>
    from .github import GitHub, GitHubEnterprise
  File "/privateDocuments/modules/github3/github.py", line 8, in <module>
    import uritemplate
ModuleNotFoundError: No module named 'uritemplate'
```

Then install that one then try again...

**Comment by ColdGrub1384** [comment]
I've found, after installing `uritemplate` that `github3.py` depends on another library, which depends on `cryptography`, which has C code :(
