### ISSUE TITLE
Installing flake8 from PyPI fails

### ISSUE THREAD

**Issue by cclauss** [ColdGrub1384/Pyto#39]
I would like to __flake8 $SCRIPT --count --select=E9,F63,F72,F82 --show-source --statistics__ but pip installing __flake8__ fails.

**Comment by ColdGrub1384** [comment]
Installing dependencies manually should work as a workaround. I'm trying to make dependencies installation work, but I'm not managing to make it work.

**Comment by cclauss** [comment]
flake8 is complicated because it is a superset of a buncha tools like pycodestyle, pyflakes, mccabe, etc.

**Comment by ColdGrub1384** [comment]
Maybe I should include it?

**Comment by cclauss** [comment]
https://pypi.org/project/entrypoints seems to be the problem.

**Comment by cclauss** [comment]
flake8 is a vital tool for me.

**Comment by ColdGrub1384** [comment]
Ok, I will include it

**Comment by cclauss** [comment]
```
Querying PyPI ... 
Downloading package ...

Installing wheel: entrypoints-0.3-py2.py3-none-any.whl...
Exception in thread Thread-5:
Traceback (most recent call last):
  File "Pyto.app/site-packages/console.py", line 155, in run
    spec.loader.exec_module(__script__)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "Pyto.app/installer.py", line 4, in <module>
    main(sys.argv[1:])
  File "Pyto.app/site-packages/pip.py", line 1372, in main
    repository.install(pkg_name, ver_spec)
  File "Pyto.app/site-packages/pip.py", line 1063, in install
    self._install(pkg_name, pkg_info, archive_filename)
  File "Pyto.app/site-packages/pip.py", line 846, in _install
    files_installed, dependencies = wheel.install(self.site_packages)
  File "Pyto.app/site-packages/stashutils/wheels.py", line 311, in install
    tfi = handler.handle_install(tp, targetdir)
  File "Pyto.app/site-packages/stashutils/wheels.py", line 159, in handle_install
    with open(tltxtp, "r") as fin:
FileNotFoundError: [Errno 2] No such file or directory: '/private/var/mobile/Containers/Data/Application/5A590060-DB9D-4E25-B672-515C6FE33D81/tmp/wheel_tmp/entrypoints-0.3-py2.py3-none-any.whl/entrypoints-0.3.dist-info/top_level.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Pyto.app/Frameworks/Python.framework/python37.zip/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "Pyto.app/Frameworks/Python.framework/python37.zip/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "Pyto.app/site-packages/console.py", line 187, in run
    EditorSplitViewController.visible.editor.showErrorAtLine(lineNumber)
AttributeError: 'NoneType' object has no attribute 'editor'

,,,

**Comment by cclauss** [comment]
Just include __entrypoints__.  I sense that __flake8__ will work fine if __entrypoints__ is present.

**Comment by cclauss** [comment]
__pyflakes $SCRIPT__ works great.

**Comment by cclauss** [comment]
__pylint__ works fairly well after step-by-step installing the dependencies (isort, etc.) that it was looking for.  The only issue is that it tries to write some log files at the end which of course fail.  I think that having pyflakes and pylint is pretty awesome!

**Comment by ColdGrub1384** [comment]
I made dependencies installation work finally! But, `entrypoints` is not installed:

```
Querying PyPI ... 
Downloading package ...

Installing wheel: flake8-3.7.7-py2.py3-none-any.whl...
Package installed: flake8
Installing dependency: entrypoints[('<', '0.4.0'), ('>=', '0.3.0')] (required by: flake8)
Querying PyPI ... 
Error: Version not found: entrypoints[('<', '0.4.0'), ('>=', '0.3.0')]
```

So, I will include `entrypoints` anyway.

**Comment by cclauss** [comment]
Perfect!  Thanks.

**Comment by ColdGrub1384** [comment]
An update was released with `entrypoints` included, and other dependencies will be installed automatically.
